version: "3.8"

services:
  app:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    healthcheck:
      # check if the postgresql server is ready to accept connections
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
#      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
#      POSTGRES_DB: ${DATABASE_DBNAME}
    ports:
      - "5432:${DATABASE_PORT}"